# Generated by Django 4.2.6 on 2025-01-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_child_company_employee_company_group_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='poisition',
        ),
        migrations.AddField(
            model_name='childcontract',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
