# Generated by Django 4.2.6 on 2025-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_poisition_childcontract_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupregistration',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
