# Generated by Django 4.2.6 on 2025-01-31 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashbox_company_salary_company_alter_cashbox_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='core.employeecontract'),
        ),
    ]
