# Generated by Django 4.2.6 on 2025-02-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_salary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.childcontract'),
        ),
    ]
