# Generated by Django 4.2.6 on 2025-02-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashbox',
        ),
    ]
