# Generated by Django 4.2.6 on 2025-02-10 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_cashbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.childcontract'),
        ),
    ]
