# Generated by Django 4.2.6 on 2025-02-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_responsible_child_childcontract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcontract',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active')], default='created'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active')], default='created'),
        ),
    ]
