# Generated by Django 5.1.6 on 2025-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
