# Generated by Django 5.1.6 on 2025-03-01 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_salary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.account'),
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paymenttype'),
        ),
    ]
